### ISSUE TITLE
Validation failure - TargetNamespace

### ISSUE THREAD

**Issue by finoradin** [MediaArea/MediaTrace#10]
Validation is failing with the following error:

System ID: http://www.mediaarea.net/mediatrace/mediatrace.xsd
Main validation file: /Users/bfino/Downloads/Untitled1.xml
Schema: http://www.mediaarea.net/mediatrace/mediatrace.xsd
Engine name: Xerces
Severity: error
Description: TargetNamespace.1: Expecting namespace 'http://www.mediaarea.net/mediatrace', but the target namespace of the schema document is 'https://mediaarea.net/mediatrace'.
Start location: 5:19

**Comment by JeromeMartinez** [comment]
I removed the www. and switched to https.
Right, that makes the 0.7.76 invalid.
I revert and put the old mediatrace.xsd on the website.

**Comment by JeromeMartinez** [comment]
https://mediaarea.net/mediatrace/mediatrace.xsd is now back with the 0.7.76 namespace.
Next version of MediaInfo will have a versioned xsd link.

**Comment by dericed** [comment]
sorry for out of sync updates to the library and the schema. The xsd now adds creation environment info and prefers https and no-www when feasible. The library should be updated against this soon. Also note that we'll start to use this format for versioning:
mediaarea.net/mediatrace/mediatrace.xsd for the latest release of the xsd and mediaarea.net/mediatrace/mediatrace_${version}.xsd for that specific version. Like [this](https://mediaarea.net/mediatrace/mediatrace_0_1.xsd).

**Comment by finoradin** [comment]
Ok it is working again
