### ISSUE TITLE
XML wellformedness 

### ISSUE THREAD

**Issue by finoradin** [MediaArea/MediaTrace#3]
Found an occurrence of unclosed `<data>` tag…

Steps to reproduce:
1) download [this file](https://support.apple.com/library/APPLE/APPLECARE_ALLGEOS/HT1425/sample_iPod.m4v.zip) 
2) $ mediainfo --Details 1 --Output=XML sample_iPod.m4v > foo.xml
3) see line 413 of foo.xml

**Comment by dericed** [comment]
for reference, line 413 is `<data offset="22165" name="Version"`.

In context: https://gist.github.com/dericed/b5e24fc5ea012c317ded#file-bad-mediatrace-L413

**Comment by JeromeMartinez** [comment]
Fixed in https://github.com/MediaArea/MediaInfoLib/commit/0734343026b9ea7c6ab512faf00cc24b4fdec767.
But this was not the only source of badformedness, other fixes in https://github.com/MediaArea/MediaInfoLib/commit/cf51b90e41f23822d5cd41882c146594023d1ecc.
