### ISSUE TITLE
validation - moreinfo not allowed in data element

### ISSUE THREAD

**Issue by finoradin** [MediaArea/MediaTrace#4]
XML validation against schema fails presently.

Attribute 'moreinfo' is not allowed to appear in element 'data'

**Comment by dericed** [comment]
Hmm, was updated here: https://github.com/MediaArea/MediaTrace/commit/c0eabb7d0743425cddacc06948d4ae5a3c4837d0.

@JeromeMartinez, can you refresh the copy of https://mediaarea.net/mediatrace/mediatrace.xsd

**Comment by JeromeMartinez** [comment]
> @JeromeMartinez, can you refresh the copy of https://mediaarea.net/mediatrace/mediatrace.xsd

done

**Comment by finoradin** [comment]
It still isn't validating – same issue

**Comment by dericed** [comment]
argh, @JeromeMartinez, put moreinfo back. Even if depreciated if it produced by the current release.

**Comment by dericed** [comment]
This commit adds it back, https://github.com/MediaArea/MediaTrace/commit/904858dd340c19f4e13799af8d89798d416795cb. Jerome can you sync the xsd to both https://mediaarea.net/mediatrace/mediatrace.xsd (current) and https://mediaarea.net/mediatrace/mediatrace_0_7_76.xsd (versioned).

**Comment by JeromeMartinez** [comment]
This was not wanted, commit error on my side, thanks for the fix.
mediatrace.xsd updated.
