### ISSUE TITLE
XML well-formedness: duplicate moreinfo attribute

### ISSUE THREAD

**Issue by finoradin** [MediaArea/MediaTrace#6]
Found a case where moreinfo attribute is repeated within one data element.

Steps to reproduce
1) download [this file](https://support.apple.com/library/APPLE/APPLECARE_ALLGEOS/HT1425/sample_3GPP.3gp.zip)
2) $ mediainfo --Details 1 --Output=XML sample\ 2.3gp    > foo.xml
3) see line 457 of foo.xml

**Comment by JeromeMartinez** [comment]
I changed "moreinfo" to "info" (same as with "block" elements), and I use the same algo, in https://github.com/MediaArea/MediaInfoLib/commit/d591fef8b94d232883c78dc817be4be377a3bbd5.
I also noticed that there are sometimes more than 4 information attributes, XSD increased to 8 attributes in https://github.com/MediaArea/MediaTrace/commit/4e5da18484b645a70a7a2789c52734e565ee746a

**Comment by JeromeMartinez** [comment]
FYI, [new XML](https://gist.github.com/JeromeMartinez/886efeba0f91d2b932ac) with current Git.
