### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaTrace#7]
@JeromeMartinez, what was the conclusion about licensing for mediatrace?

**Comment by JeromeMartinez** [comment]
MediaTrace output is a feature of MediaInfo, so code has the same license (BSD-2 Clause)
MediaTrace XSD should have the same license.

**Comment by ablwr** [comment]
https://github.com/MediaArea/MediaTrace/commit/6f25340dc70e402a45129ccea0aed549c9dd99b6 resolves
